[workspace]
members = ["tlcs", "x/timelock"]

[workspace.dependencies]
gears = { git = "https://github.com/rumos-io/gears", rev = "9aa4138" }
proto-types = { git = "https://github.com/rumos-io/gears", rev = "9aa4138" }
proto-messages = { git = "https://github.com/rumos-io/gears", rev = "9aa4138" }
database = { git = "https://github.com/rumos-io/gears", rev = "9aa4138" }
auth = { git = "https://github.com/rumos-io/gears", rev = "9aa4138" }
store = { git = "https://github.com/rumos-io/gears", rev = "9aa4138" }
bank = { git = "https://github.com/rumos-io/gears", rev = "9aa4138" }

ibc-proto = { git = "https://github.com/joneskm/ibc-proto-rs" }
